### Bits:
**1a**. **`8 bits`**
**1b**. **`64 bits`**

### Results from Operations:
**2**. `-1 1`  
**3**. `16`  
**4**. `1 0`  
**5**. `0 0`  

### Operators and Overloading:
**6**. Operators that can be overloaded:  
    - **(b)** `%`  
    - **(d)** `==`

### Output of Code Snippets:
**7**. `10`  
**8**.  
    `1`  
    `3`   
    `4`   
    `2`  
    

**9**. `0 0`  
**10**.  
    `1 0`  
    `2 1`  
    `1.2 0`  
    


In [49]:
import qflib as qf
import numpy as np

In [50]:
l = [np.array([1.]), np.array([1., 1.])]
for i in range(6):
    l.append(qf.polyProd(l[1], l[-1]))
for row in l:
    print(row)

[1.]
[1. 1.]
[1. 2. 1.]
[1. 3. 3. 1.]
[1. 4. 6. 4. 1.]
[ 1.  5. 10. 10.  5.  1.]
[ 1.  6. 15. 20. 15.  6.  1.]
[ 1.  7. 21. 35. 35. 21.  7.  1.]
